// Mock Products
export const mockProducts = []

// Mock Orders
export const mockOrders = [
  {
    id: "ORD-1234",
    customer: "John Smith",
    email: "john.smith@example.com",
    date: "2023-11-10",
    status: "completed",
    total: 349,
    items: 1,
  },
  {
    id: "ORD-1233",
    customer: "Sarah Johnson",
    email: "sarah.j@example.com",
    date: "2023-11-09",
    status: "processing",
    total: 1299,
    items: 2,
  },
  {
    id: "ORD-1232",
    customer: "Mike Williams",
    email: "mike.w@example.com",
    date: "2023-11-08",
    status: "shipped",
    total: 899,
    items: 1,
  },
  {
    id: "ORD-1231",
    customer: "Emily Davis",
    email: "emily.d@example.com",
    date: "2023-11-07",
    status: "pending",
    total: 749,
    items: 3,
  },
  {
    id: "ORD-1230",
    customer: "Robert Johnson",
    email: "robert.j@example.com",
    date: "2023-11-06",
    status: "cancelled",
    total: 599,
    items: 2,
  },
]

// Mock Customers
export const mockCustomers = [
  {
    id: "CUST-1001",
    name: "John Smith",
    email: "john.smith@example.com",
    joinDate: "2023-05-15",
    orders: 5,
    totalSpent: 1249,
    status: "active",
  },
  {
    id: "CUST-1002",
    name: "Sarah Johnson",
    email: "sarah.j@example.com",
    joinDate: "2023-06-22",
    orders: 3,
    totalSpent: 2199,
    status: "active",
  },
  {
    id: "CUST-1003",
    name: "Mike Williams",
    email: "mike.w@example.com",
    joinDate: "2023-07-10",
    orders: 2,
    totalSpent: 899,
    status: "active",
  },
  {
    id: "CUST-1004",
    name: "Emily Davis",
    email: "emily.d@example.com",
    joinDate: "2023-08-05",
    orders: 1,
    totalSpent: 749,
    status: "inactive",
  },
  {
    id: "CUST-1005",
    name: "Robert Johnson",
    email: "robert.j@example.com",
    joinDate: "2023-09-18",
    orders: 4,
    totalSpent: 1599,
    status: "active",
  },
]

// Product Categories
export const productCategories = [
  "Apparel > Merchandise",
  "AN Fittings & Lines > AN Fittings",
  "AN Fittings & Lines > AN Adapters",
  "AN Fittings & Lines > AN Lines & Hose",
  "AN Fittings & Lines > AN Accessories",
  "Engine Components > Fuel Rails",
  "Engine Components > Oil System",
  "Engine Components > Throttle Bodies",
  "Engine Components > Engine Management",
  "Engine Components > Cooling Components",
  "Turbo & Forced Induction > Turbochargers",
  "Turbo & Forced Induction > Intercoolers",
  "Turbo & Forced Induction > Wastegates & BOV",
  "Turbo & Forced Induction > Turbo Accessories",
  "Turbo & Forced Induction > Heat Management",
  "Fuel System > Fuel Cells",
  "Fuel System > Fuel Pumps",
  "Fuel System > Fuel Lines",
  "Fuel System > Fuel Regulators",
  "Fuel System > Fuel Accessories",
  "Tools & Equipment > Hand Tools",
  "Tools & Equipment > Fabrication Tools",
  "Tools & Equipment > Measurement Tools",
  "Tools & Equipment > Installation Tools",
  "Consumables > Nuts & Bolts",
  "Consumables > Gaskets & Seals",
  "Consumables > Cleaning Products",
  "Consumables > Installation Supplies",
  "Wheel & Brake Systems > Brake Components",
  "Wheel & Brake Systems > Wheel Accessories",
  "Wheel & Brake Systems > E-Brake Components",
  "Custom Fabrication > Custom Work",
  "Custom Fabrication > Fabrication Services",
  "Custom Fabrication > Installation Services"
]

